apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-app-production
  namespace: argocd           # Argo CD itself watches this namespace
spec:
  project: default
  source:
    repoURL: 'https://github.com/NissimAmira/DevOpsProject.git'
    targetRevision: main
    path: helm/hello-world-app
    helm:
      valueFiles:
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world-production
  syncPolicy:
    automated:
      prune: true               # delete resources removed from Git
      selfHeal: true            # fix drift automatically
    syncOptions:
      - CreateNamespace=true    # ensure namespace exists